### ISSUE TITLE
Doc suggests pip3 for install, Anaconda seems to work with pip only

### ISSUE THREAD

**Issue by torridgristle** [hahnec/color-matcher#3]
I'm using Anaconda (Conda 4.9.2) and used the documentation's suggested pip3 install procedure for color-matcher, but I couldn't run it from the command prompt. However, when I installed it via pip (just pip) it worked fine.

I ain't entirely sure if this fella got Python 3.8 and Python 2.7 both in there, but somehow I can only get it to run by entering only `color-matcher` in the command line after installing through pip as opposed to pip3.

Might need an extra line in the documentation saying do this if you're using Anaconda or Python 2.x or something, I ain't entirely sure of what's going on behind the scenes really.

**Comment by hahnec** [comment]
The `color-matcher` module is currently tested with [Python 3.5, 3.8 and 3.9](https://github.com/hahnec/color-matcher/actions) for a variety of platforms (Linux, Win and macOS). Python 2.x is not covered and generally discouraged as support ran out last year. As I never used Anaconda, I am not sure how `conda` interacts with the Python Package Index (PyPI), which serves `pip` commands. Thus, I recommend reading the [Anaconda - Using pip in an environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#using-pip-in-an-environment) on how to integrate `pip`.
